### ISSUE TITLE
Wrong bytes/block values in ispc_texcomp.h comment

### ISSUE THREAD

**Issue by akbyrd** [GameTechDev/ISPCTextureCompressor#19]
The notes in ispc_texcomp.h list the number of bytes per block necessary for BC1 as 4 and for BC3 as 8. It looks like these should actually be 8 and 16.

https://github.com/GameTechDev/ISPCTextureCompressor/blob/master/ISPC%20Texture%20Compressor/ispc_texcomp/ispc_texcomp.h#L103

https://docs.microsoft.com/en-us/windows/desktop/direct3d10/d3d10-graphics-programming-guide-resources-block-compression
https://docs.microsoft.com/en-us/windows/desktop/direct3d11/texture-block-compression-in-direct3d-11

**Comment by gwihlidal** [comment]
I just came across this issue now as well, looking to file an issue for it. Can we get this updated please so users of the library ensure the dst is allocated with the correct memory range?
