### ISSUE TITLE
DXT1 compression on images with smooth gradients results in banding

### ISSUE THREAD

**Issue by mjmvisser** [GameTechDev/ISPCTextureCompressor#21]
Original:

![YdRYKNe](https://user-images.githubusercontent.com/351739/54757037-cbb53d00-4bbf-11e9-8fa1-7835e7c0a404.png)

DXT1 compressed:

![Screen Shot 2019-03-21 at 9 59 08 AM](https://user-images.githubusercontent.com/351739/54757153-09b26100-4bc0-11e9-9705-47a0483acbb1.png)

![Screen Shot 2019-03-21 at 10 03 36 AM](https://user-images.githubusercontent.com/351739/54757441-9e1cc380-4bc0-11e9-9c9f-aadd982237e8.png)

**Comment by ghost** [comment]
Hi,

    DXT1 compresses to two 16-bit RGB 5:6:5 colour values per 4x4 block. So banding is unavoidable. Try loading the texture in Photoshop and do a Posterise at 64 levels.....this is essentially what's happening, although the red and blue channels only have 32 values so it's even worse.
   You will get better results using BC7.

Bill.

**Comment by DaveBookout-Intel** [comment]
You could also try adding noise to your image before compressing. 

gradient:
<img width="400" alt="gradient_bc1" src="https://user-images.githubusercontent.com/78050722/113951427-647b7d00-97c8-11eb-9116-7987cdc860ce.PNG">

gradient + noise:
<img width="399" alt="gradient_noise_bc1" src="https://user-images.githubusercontent.com/78050722/113951423-62b1b980-97c8-11eb-864b-7b67386e9e48.PNG">
