### ISSUE TITLE
BC7 determinism

### ISSUE THREAD

**Issue by sfider** [GameTechDev/ISPCTextureCompressor#8]
Hi,

I have a problem with BC7 compression output no being deterministic. I read that there was such an issue before and it ought to be fixed, but here it is. I tried to force initialization of some local arrays, but this didn't help. Can there be anything done about this?

Thanks

**Comment by MarcFauconneau** [comment]
pics or it didn't happen

**Comment by sfider** [comment]
Few examples as requested:
[example.zip](https://github.com/GameTechDev/ISPCTextureCompressor/files/410703/example.zip)

**Comment by MarcFauconneau** [comment]
I can't seem to reproduce similar files at all, and I tried all profiles. What exactly did you use?

**Comment by sfider** [comment]
I used basic profile:
    mode_selection: {true, true, true, true}
    refineIterations: {2, 2, 2, 2, 2, 2, 2, -858993460}
    skip_mode2: true
    fastSkipTreshold_mode1: 12
    fastSkipTreshold_mode3: 8
    fastSkipTreshold_mode7: 0
    mode45_channel0: 0
    refineIterations_channel: 2
    channels: 3

I'm using multiple threads for compression of one texture slicing it to 8 equal parts if possible. Using one thread per texture didn't help.

**Comment by sfider** [comment]
I've prepared examples done on single thread with no other thread working simultaneously: [example_singlethread.zip](https://github.com/GameTechDev/ISPCTextureCompressor/files/419832/example_singlethread.zip)

**Comment by MarcFauconneau** [comment]
I am definitively not getting the same results with the basic profile. Are you sure you are using the last version on the repository?

Also, can you avoid mipmaps in your examples? The main textures in your examples 01, 03 & 04 are exactly the same...

**Comment by sfider** [comment]
Yes, I'm using the latest version. I've done some changes with initializing local arrays, but it shouldn't make a difference for worse?

As for mipmaps, they just give more examples, I suppose. I've tested that each time mipmaps are generated the same. The difference appears after compression. I'll double check if I didn't miss anything [EDITED: I forgot my own files naming]

Is there any chance that heavy use of multithreading could break something? I looked through the code, and couldn't find anything.

I'll try to prepare some isolated code that will exhibit this nondeterministic behaviour.

**Comment by MarcFauconneau** [comment]
I saw one block difference in picture 02, that's it. But what concerns me more is that I can't reproduce your results at all from the .tga file, 

Basic profile produces completely different results, with significantly higher quality. For instance:

01_a.dds: RGB psnr = 46.305 dB (01_b is exactly the same data)
basic profile: RGB psnr = 46.778 dB
(using 01.tga as a reference for all)

**Comment by sfider** [comment]
My bad, I've rebuild the library, but forgot to swap the DLL file. So I was using the old version all along. Everything is fine now.
